services:
  tookhook:
    image: ghcr.io/k1nky/tookhook:v1.0.0-pre
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config:ro
    environment:
      - TOOKHOOK_LOG_LEVEL=info
      - TOOKHOOK_SERVER_LISTEN=:8080
      - TOOKHOOK_QUEUE_ADDR=redis:6379
      - TOOKHOOK_QUEUE_DB=0
      - TOOKHOOK_QUEUE_CONCURRENCY=10
      - TOOKHOOK_CONFIG=/app/config/config.example.yaml
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  asynqmon:
    image: hibiken/asynqmon:0.7.1
    ports:
      - 8088:8080
    command:
      - -redis-addr=redis:6379

volumes:
  redis_data: