services:
  tookhook:
    environment:
      TOOKHOOK_LISTEN: 0.0.0.0:8080
      TOOKHOOK_LOG_LEVEL: debug
      TOOKHOOK_PLUGINS: /app/pachca,/app/telegram
      TOOKHOOK_DATABASE_URI: file:///app/config/hooks.yml
      TOOKHOOK_QUEUE_URI: redis:6379
    ports:
      - 8080:8080
    image: k1nky/tookhook:v0.4.0rc1
    volumes:
      - ./config:/app/config:ro
  redis:
    image: docker.io/redis:7-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes
    # - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    # env_file: env/redis.env
    volumes:
    - redis-data:/data
    ports:
      - 6379:6379
  asynqmon:
    image: hibiken/asynqmon:0.7.1
    ports:
      - 8088:8080
    command:
      - -redis-addr=redis:6379
volumes:
  redis-data:
    driver: local
