// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package builtin

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6252c418DecodeGithubComK1nkyTookhookInternalBuiltin(in *jlexer.Lexer, out *HttpHandlerOptions) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "method":
			out.Method = string(in.String())
		case "url":
			out.URL = string(in.String())
		case "timeout":
			out.Timeout = uint(in.Uint())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6252c418EncodeGithubComK1nkyTookhookInternalBuiltin(out *jwriter.Writer, in HttpHandlerOptions) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix[1:])
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	{
		const prefix string = ",\"timeout\":"
		out.RawString(prefix)
		out.Uint(uint(in.Timeout))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HttpHandlerOptions) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6252c418EncodeGithubComK1nkyTookhookInternalBuiltin(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HttpHandlerOptions) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6252c418EncodeGithubComK1nkyTookhookInternalBuiltin(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HttpHandlerOptions) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6252c418DecodeGithubComK1nkyTookhookInternalBuiltin(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HttpHandlerOptions) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6252c418DecodeGithubComK1nkyTookhookInternalBuiltin(l, v)
}
