// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.2
// source: pkg/plugin/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginOptions) Reset() {
	*x = PluginOptions{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginOptions) ProtoMessage() {}

func (x *PluginOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginOptions.ProtoReflect.Descriptor instead.
func (*PluginOptions) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginOptions) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ReceiverSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *PluginOptions         `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiverSpec) Reset() {
	*x = ReceiverSpec{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiverSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiverSpec) ProtoMessage() {}

func (x *ReceiverSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiverSpec.ProtoReflect.Descriptor instead.
func (*ReceiverSpec) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiverSpec) GetOptions() *PluginOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      *ReceiverSpec          `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	PluginOptions *PluginOptions         `protobuf:"bytes,3,opt,name=plugin_options,json=pluginOptions,proto3" json:"plugin_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ForwardRequest) GetReceiver() *ReceiverSpec {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *ForwardRequest) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ForwardRequest) GetPluginOptions() *PluginOptions {
	if x != nil {
		return x.PluginOptions
	}
	return nil
}

type ForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ForwardResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginOptions *PluginOptions         `protobuf:"bytes,1,opt,name=plugin_options,json=pluginOptions,proto3" json:"plugin_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateRequest) GetPluginOptions() *PluginOptions {
	if x != nil {
		return x.PluginOptions
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{6}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{7}
}

var File_pkg_plugin_proto_plugin_proto protoreflect.FileDescriptor

const file_pkg_plugin_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/plugin/proto/plugin.proto\x12\rprotocol.grpc\"%\n" +
	"\rPluginOptions\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"F\n" +
	"\fReceiverSpec\x126\n" +
	"\aoptions\x18\x03 \x01(\v2\x1c.protocol.grpc.PluginOptionsR\aoptions\"\x1a\n" +
	"\x04Data\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xb7\x01\n" +
	"\x0eForwardRequest\x127\n" +
	"\breceiver\x18\x01 \x01(\v2\x1b.protocol.grpc.ReceiverSpecR\breceiver\x12'\n" +
	"\x04data\x18\x02 \x01(\v2\x13.protocol.grpc.DataR\x04data\x12C\n" +
	"\x0eplugin_options\x18\x03 \x01(\v2\x1c.protocol.grpc.PluginOptionsR\rpluginOptions\"%\n" +
	"\x0fForwardResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"V\n" +
	"\x0fValidateRequest\x12C\n" +
	"\x0eplugin_options\x18\x01 \x01(\v2\x1c.protocol.grpc.PluginOptionsR\rpluginOptions\"\x12\n" +
	"\x10ValidateResponse\"\a\n" +
	"\x05Empty2\xd5\x01\n" +
	"\x06Plugin\x12H\n" +
	"\aForward\x12\x1d.protocol.grpc.ForwardRequest\x1a\x1e.protocol.grpc.ForwardResponse\x124\n" +
	"\x06Health\x12\x14.protocol.grpc.Empty\x1a\x14.protocol.grpc.Empty\x12K\n" +
	"\bValidate\x12\x1e.protocol.grpc.ValidateRequest\x1a\x1f.protocol.grpc.ValidateResponseB,Z*github.com/k1nky/tookhook/pkg/plugin/protob\x06proto3"

var (
	file_pkg_plugin_proto_plugin_proto_rawDescOnce sync.Once
	file_pkg_plugin_proto_plugin_proto_rawDescData []byte
)

func file_pkg_plugin_proto_plugin_proto_rawDescGZIP() []byte {
	file_pkg_plugin_proto_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_plugin_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_proto_rawDesc), len(file_pkg_plugin_proto_plugin_proto_rawDesc)))
	})
	return file_pkg_plugin_proto_plugin_proto_rawDescData
}

var file_pkg_plugin_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_plugin_proto_plugin_proto_goTypes = []any{
	(*PluginOptions)(nil),    // 0: protocol.grpc.PluginOptions
	(*ReceiverSpec)(nil),     // 1: protocol.grpc.ReceiverSpec
	(*Data)(nil),             // 2: protocol.grpc.Data
	(*ForwardRequest)(nil),   // 3: protocol.grpc.ForwardRequest
	(*ForwardResponse)(nil),  // 4: protocol.grpc.ForwardResponse
	(*ValidateRequest)(nil),  // 5: protocol.grpc.ValidateRequest
	(*ValidateResponse)(nil), // 6: protocol.grpc.ValidateResponse
	(*Empty)(nil),            // 7: protocol.grpc.Empty
}
var file_pkg_plugin_proto_plugin_proto_depIdxs = []int32{
	0, // 0: protocol.grpc.ReceiverSpec.options:type_name -> protocol.grpc.PluginOptions
	1, // 1: protocol.grpc.ForwardRequest.receiver:type_name -> protocol.grpc.ReceiverSpec
	2, // 2: protocol.grpc.ForwardRequest.data:type_name -> protocol.grpc.Data
	0, // 3: protocol.grpc.ForwardRequest.plugin_options:type_name -> protocol.grpc.PluginOptions
	0, // 4: protocol.grpc.ValidateRequest.plugin_options:type_name -> protocol.grpc.PluginOptions
	3, // 5: protocol.grpc.Plugin.Forward:input_type -> protocol.grpc.ForwardRequest
	7, // 6: protocol.grpc.Plugin.Health:input_type -> protocol.grpc.Empty
	5, // 7: protocol.grpc.Plugin.Validate:input_type -> protocol.grpc.ValidateRequest
	4, // 8: protocol.grpc.Plugin.Forward:output_type -> protocol.grpc.ForwardResponse
	7, // 9: protocol.grpc.Plugin.Health:output_type -> protocol.grpc.Empty
	6, // 10: protocol.grpc.Plugin.Validate:output_type -> protocol.grpc.ValidateResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_plugin_proto_plugin_proto_init() }
func file_pkg_plugin_proto_plugin_proto_init() {
	if File_pkg_plugin_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_proto_rawDesc), len(file_pkg_plugin_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugin_proto_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_plugin_proto_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_plugin_proto_plugin_proto_msgTypes,
	}.Build()
	File_pkg_plugin_proto_plugin_proto = out.File
	file_pkg_plugin_proto_plugin_proto_goTypes = nil
	file_pkg_plugin_proto_plugin_proto_depIdxs = nil
}
