// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package hooks

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEa0bc929DecodeGithubComK1nkyTookhookInternalEntityHooks(in *jlexer.Lexer, out *Hook) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Meta":
			easyjsonEa0bc929DecodeGithubComK1nkyTookhookInternalEntityHooks1(in, &out.Meta)
		case "Args":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Args = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 string
					v1 = string(in.String())
					(out.Args)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "RawBody":
			if in.IsNull() {
				in.Skip()
				out.RawBody = nil
			} else {
				out.RawBody = in.Bytes()
			}
		case "Encoding":
			out.Encoding = ContentEncoding(in.Int())
		case "Headers":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Headers = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v3 string
					v3 = string(in.String())
					(out.Headers)[key] = v3
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEa0bc929EncodeGithubComK1nkyTookhookInternalEntityHooks(out *jwriter.Writer, in Hook) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Meta\":"
		out.RawString(prefix[1:])
		easyjsonEa0bc929EncodeGithubComK1nkyTookhookInternalEntityHooks1(out, in.Meta)
	}
	{
		const prefix string = ",\"Args\":"
		out.RawString(prefix)
		if in.Args == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v4First := true
			for v4Name, v4Value := range in.Args {
				if v4First {
					v4First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v4Name))
				out.RawByte(':')
				out.String(string(v4Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"RawBody\":"
		out.RawString(prefix)
		out.Base64Bytes(in.RawBody)
	}
	{
		const prefix string = ",\"Encoding\":"
		out.RawString(prefix)
		out.Int(int(in.Encoding))
	}
	{
		const prefix string = ",\"Headers\":"
		out.RawString(prefix)
		if in.Headers == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v7First := true
			for v7Name, v7Value := range in.Headers {
				if v7First {
					v7First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v7Name))
				out.RawByte(':')
				out.String(string(v7Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Hook) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEa0bc929EncodeGithubComK1nkyTookhookInternalEntityHooks(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Hook) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEa0bc929EncodeGithubComK1nkyTookhookInternalEntityHooks(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Hook) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEa0bc929DecodeGithubComK1nkyTookhookInternalEntityHooks(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Hook) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEa0bc929DecodeGithubComK1nkyTookhookInternalEntityHooks(l, v)
}
func easyjsonEa0bc929DecodeGithubComK1nkyTookhookInternalEntityHooks1(in *jlexer.Lexer, out *Meta) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			out.ID = uint64(in.Uint64())
		case "Name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEa0bc929EncodeGithubComK1nkyTookhookInternalEntityHooks1(out *jwriter.Writer, in Meta) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}
