// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock/monitor.go -package=mock storage
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/k1nky/tookhook/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mockpluginmanager is a mock of pluginmanager interface.
type Mockpluginmanager struct {
	ctrl     *gomock.Controller
	recorder *MockpluginmanagerMockRecorder
}

// MockpluginmanagerMockRecorder is the mock recorder for Mockpluginmanager.
type MockpluginmanagerMockRecorder struct {
	mock *Mockpluginmanager
}

// NewMockpluginmanager creates a new mock instance.
func NewMockpluginmanager(ctrl *gomock.Controller) *Mockpluginmanager {
	mock := &Mockpluginmanager{ctrl: ctrl}
	mock.recorder = &MockpluginmanagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockpluginmanager) EXPECT() *MockpluginmanagerMockRecorder {
	return m.recorder
}

// Health mocks base method.
func (m *Mockpluginmanager) Health(ctx context.Context) entity.PluginsStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx)
	ret0, _ := ret[0].(entity.PluginsStatus)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockpluginmanagerMockRecorder) Health(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*Mockpluginmanager)(nil).Health), ctx)
}

// MockhookService is a mock of hookService interface.
type MockhookService struct {
	ctrl     *gomock.Controller
	recorder *MockhookServiceMockRecorder
}

// MockhookServiceMockRecorder is the mock recorder for MockhookService.
type MockhookServiceMockRecorder struct {
	mock *MockhookService
}

// NewMockhookService creates a new mock instance.
func NewMockhookService(ctrl *gomock.Controller) *MockhookService {
	mock := &MockhookService{ctrl: ctrl}
	mock.recorder = &MockhookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhookService) EXPECT() *MockhookServiceMockRecorder {
	return m.recorder
}

// Health mocks base method.
func (m *MockhookService) Health(ctx context.Context) entity.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx)
	ret0, _ := ret[0].(entity.Status)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockhookServiceMockRecorder) Health(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockhookService)(nil).Health), ctx)
}

// Mockstorage is a mock of storage interface.
type Mockstorage struct {
	ctrl     *gomock.Controller
	recorder *MockstorageMockRecorder
}

// MockstorageMockRecorder is the mock recorder for Mockstorage.
type MockstorageMockRecorder struct {
	mock *Mockstorage
}

// NewMockstorage creates a new mock instance.
func NewMockstorage(ctrl *gomock.Controller) *Mockstorage {
	mock := &Mockstorage{ctrl: ctrl}
	mock.recorder = &MockstorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockstorage) EXPECT() *MockstorageMockRecorder {
	return m.recorder
}

// Mocklogger is a mock of logger interface.
type Mocklogger struct {
	ctrl     *gomock.Controller
	recorder *MockloggerMockRecorder
}

// MockloggerMockRecorder is the mock recorder for Mocklogger.
type MockloggerMockRecorder struct {
	mock *Mocklogger
}

// NewMocklogger creates a new mock instance.
func NewMocklogger(ctrl *gomock.Controller) *Mocklogger {
	mock := &Mocklogger{ctrl: ctrl}
	mock.recorder = &MockloggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklogger) EXPECT() *MockloggerMockRecorder {
	return m.recorder
}

// Debugf mocks base method.
func (m *Mocklogger) Debugf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockloggerMockRecorder) Debugf(template any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*Mocklogger)(nil).Debugf), varargs...)
}

// Errorf mocks base method.
func (m *Mocklogger) Errorf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockloggerMockRecorder) Errorf(template any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*Mocklogger)(nil).Errorf), varargs...)
}
